Added Extcodes, requirement checks and timeout

diff --git a/qnap_health b/qnap_health
--- a/qnap_health
+++ b/qnap_health
@@ -33,6 +33,7 @@ usage() {
   echo "       -h                    - no human-readable output; do not use unit suffixes"
   echo "       -w|--warning          - warning"
   echo "       -c|--critical         - critical"
+  echo "       -t|--timeout          - timeout for snmp connect, default: 5s"
   echo "       --help                - show this help"
   echo
   echo "SNMP specific"
@@ -64,14 +65,55 @@ usage() {
   echo " Example for fans: ${0##*/} -H 127.0.0.1 -C public -p fans -w 2000 -c 1900"
   echo "                   critical and warning are minimum speed in rpm for fans"
   echo
-  exit 3
+  echo " this plugin requires the following programs to be installed:"
+  echo "  * bc"
+  echo "  * awk"
+  echo "  * snmpget"
+  echo "  * snmpwalk"
+  exit $EXIT_UNKOWN
 }
 
+# Default values
 strProtocol="2c"
 strCommunity="public"
 strPort="161"
+timeout="5"
 
-PARSED_OPTIONS=$(getopt -n "$0" -o V:H:C:p:hw:c:l:u:a:A:x:X:P: --long "hostname:,community:,part:,warning:,critical:,level:,user:,authprotocol:,authpassphrase:,privprotocol:,privpassphrase:,port:,help" -- "$@")
+# Exit codes
+EXIT_OK="0"
+EXIT_WARNING="1"
+EXIT_CRITICAL="2"
+EXIT_UNKNOWN="3"
+
+# check for needed programs
+SNMPGET_BIN=$(which snmpget)
+SNMPWALK_BIN=$(which snmpwalk)
+BC_BIN=$(which bc)
+AWK_BIN=$(which awk)
+
+if [ -z "$SNMPGET_BIN" ]; then
+  echo "Could not find 'snmpget'!"
+  usage()
+fi
+
+if [ -z "$SNMPWALK_BIN" ]; then
+  echo "Could not find 'snmpwalk'!"
+  usage()
+fi
+
+if [ -z "$BC_BIN" ]; then
+  echo "Could not find 'bc'!"
+  usage()
+fi
+
+if [ -z "$AWK_BIN" ]; then
+  echo "Could not find 'awk'!"
+  usage()
+fi
+
+# Options
+
+PARSED_OPTIONS=$(getopt -n "$0" -o V:H:C:p:hw:c:t:l:u:a:A:x:X:P: --long "hostname:,community:,part:,warning:,critical:,timeout:,level:,user:,authprotocol:,authpassphrase:,privprotocol:,privpassphrase:,port:,help" -- "$@")
 if [ $? -ne 0 ]; then
   usage
   exit 3
@@ -117,7 +159,7 @@ while true; do
             ;;
           *)
             echo "ERROR: wrong protocol version" >&2
-            exit 3
+            usage()
             ;;
         esac
       fi
@@ -131,6 +173,10 @@ while true; do
       strCritical="$2"
       shift 2
       ;;
+    -t|--timeout)
+      timeout="$2"
+      shift 2
+      ;;
     -l|--level)
       if [ -n "$2" ]; then
         strLevel="$2"
@@ -139,7 +185,7 @@ while true; do
             ;;
           *)
             echo "ERROR: wrong security level" >&2
-            exit 3
+            usage()
             ;;
         esac
       fi
@@ -159,7 +205,7 @@ while true; do
             ;;
           *)
             echo "ERROR: wrong authentication protocol" >&2
-            exit 3
+            usage()
             ;;
         esac
       fi
@@ -170,7 +216,7 @@ while true; do
         strAuthpassphrase="$2"
       else
         echo "ERROR: authentification passphrase is missing" >&2
-        exit 3
+        usage()
       fi
       shift 2
       ;;
@@ -182,7 +228,7 @@ while true; do
             ;;
           *)
             echo "ERROR: wrong privacy protocol" >&2
-            exit 3
+            usage()
             ;;
         esac
       fi
@@ -228,6 +274,10 @@ function _cmdparam() {
   echo "$cmd"
 }
 
+function _trim() {
+  return $(echo $1 | awk '{$1=$1};1')
+}
+
 function _snmpget() {
   snmpget $(_cmdparam) "$@"
 }
@@ -257,10 +307,10 @@ function _get_exp() {
 }
 
 # Check if QNAP is online
-TEST="$(_snmpstatus -t 5 -r 0 2>&1)"
+TEST="$(_snmpstatus -t $timeout -r 0 2>&1)"
 if [ "$TEST" == "Timeout: No Response from $strHostname" ]; then
   echo "UNKOWN: SNMP to $strHostname is not available or wrong community string";
-  exit 3;
+  exit $EXIT_UNKNOWN;
 fi
 
 # STATUS ---------------------------------------------------------------------------------------------------------------------------------------
@@ -307,13 +357,13 @@ elif [ "$strPart" == "diskused" ]; then
 
   if [ $perc -ge $strCritical ]; then
     echo "CRITICAL: $OUTPUT"
-    exit 2
+    exit $EXIT_CRITICAL 
   elif [ $perc -ge $strWarning ]; then
     echo "WARNING: $OUTPUT"
-    exit 1
+    exit $EXIT_WARNING
   else
     echo "OK: $OUTPUT"
-    exit 0
+    exit $EXIT_OK
   fi
 
 # CPU ----------------------------------------------------------------------------------------------------------------------------------------------
@@ -324,13 +374,13 @@ elif [ "$strPart" == "cpu" ]; then
 
   if (( $(echo "$CPU > $strCritical" | bc -l) )); then
     echo "CRITICAL: $OUTPUT"
-    exit 2
+    exit $EXIT_CRITICAL
   elif ((  $(echo "$CPU > $strWarning" | bc -l) )); then
     echo "WARNING: $OUTPUT"
-    exit 1
+    exit $EXIT_WARNING
   else
     echo "OK: $OUTPUT"
-    exit 0
+    exit $EXIT_OK
   fi
 
 # CPUTEMP ----------------------------------------------------------------------------------------------------------------------------------------------
@@ -340,13 +390,13 @@ elif [ "$strPart" == "cputemp" ]; then
 
   if [ "$TEMP0" -ge "$strCritical" ]; then
     echo "CRITICAL: $OUTPUT"
-    exit 2
+    exit $EXIT_CRITICAL
   elif [ "$TEMP0" -ge "$strWarning" ]; then
       echo "WARNING: $OUTPUT"
-      exit 1
+      exit $EXIT_WARNING
   else
     echo "OK: $OUTPUT"
-    exit 0
+    exit $EXIT_OK
   fi
 
 # Free RAM---------------------------------------------------------------------------------------------------------------------------------------
@@ -386,13 +436,13 @@ elif [ "$strPart" == "freeram" ]; then
 
   if [ $percMem -ge $strCritical ]; then
     echo "CRITICAL: $OUTPUT"
-    exit 2
+    exit $EXIT_CRITICAL
   elif [ $percMem -ge $strWarning ]; then
     echo "WARNING: $OUTPUT"
-    exit 1
+    exit $EXIT_WARNING
   else
     echo "OK: $OUTPUT"
-    exit 0
+    exit $EXIT_OK
   fi
 
 # System Temperature---------------------------------------------------------------------------------------------------------------------------------------
@@ -402,13 +452,13 @@ elif [ "$strPart" == "temp" ]; then
 
   if [ "$TEMP0" -ge "$strCritical" ]; then
     echo "CRITICAL: $OUTPUT"
-    exit 2
+    exit $EXIT_CRITICAL
   elif [ "$TEMP0" -ge "$strWarning" ]; then
     echo "WARNING: $OUTPUT"
-    exit 1
+    exit $EXIT_WARNING
   else
     echo "OK: $OUTPUT"
-    exit 0
+    exit $EXIT_OK
   fi
 
 
@@ -456,18 +506,18 @@ elif [[ "$strPart" == hdtemp ]]; then
     OUTPUT="OK: All HDD are fine."
   else
     if [ -n "$CriticalStr" ]; then
-      EXIT=2
+      EXIT=$EXIT_CRITICAL
       OUTPUT="$CriticalStr"
     fi
     if [ -n "$WarningStr" ]; then
       if [ ! $EXIT -eq 2 ]; then
-        EXIT=1
+        EXIT=$EXIT_WARNING
       fi
       OUTPUT="$OUTPUT $WarningStr"
     fi
     if [ -n "$UnknownStr" ];then
       if [ ! $EXIT -eq 1 -o ! $EXIT -eq 2 ];then
-        EXIT=3
+        EXIT=$EXIT_UNKNOWN
       fi
       OUTPUT="$OUTPUT $UnknownStr"
     fi
@@ -503,10 +553,10 @@ elif [ "$strPart" == "hdstatus" ]; then
   if [ -n "$output_crit" ]
   then
     echo "CRITICAL: $(echo ${output_crit} | awk '{$1=$1};1' )$PERFDATA"
-    exit 2
+    exit $EXIT_CRITICAL
   else
     echo "OK: Online Disk $hdok, Free Slot ${hdnop}$PERFDATA"
-    exit 0
+    exit $EXIT_OK
   fi
 
 # LUN Status----------------------------------------------------------------------------------------------------------------------------------------
@@ -570,11 +620,11 @@ elif [ "$strPart" == "lunstatus" ]; then
   echo "$ALLOUTPUT| $PERFOUTPUT"
 
   if [ $CRITICAL -eq 1 ]; then
-    exit 2
+    exit $EXIT_CRITICAL
   elif [ $WARNING -eq 1 ]; then
-    exit 1
+    exit $EXIT_WARNING
   else
-    exit 0
+    exit $EXIT_OK
   fi
 # Volume Status----------------------------------------------------------------------------------------------------------------------------------------
 elif [ "$strPart" == "volstatus" ]; then
@@ -659,11 +709,11 @@ elif [ "$strPart" == "volstatus" ]; then
   echo "$ALLOUTPUT|$PERFOUTPUT"
 
   if [ $CRITICAL -eq 1 ]; then
-    exit 2
+    exit $EXIT_CRITICAL
   elif [ $WARNING -eq 1 ]; then
-    exit 1
+    exit $EXIT_WARNING
   else
-    exit 0
+    exit $EXIT_OK
   fi
 
 # Power Supply Status  ----------------------------------------------------------------------------------------------------------------------------------
@@ -676,7 +726,7 @@ elif [ "$strPart" == "powerstatus" ]; then
 
   if [[ "$COUNT" == 'No Such Object'* ]]; then
     echo "UNKOWN: Could not get information about powersupplies"
-    exit 4
+    exit $EXIT_UNKNOWN
   fi
 
   while [ "$PS" -le "$COUNT" ]; do
@@ -697,11 +747,11 @@ elif [ "$strPart" == "powerstatus" ]; then
   echo "$ALLOUTPUT"
 
   if [ $CRITICAL -eq 1 ]; then
-    exit 2
+    exit $EXIT_CRITICAL
   elif [ $WARNING -eq 1 ]; then
-    exit 1
+    exit $EXIT_WARNING
   else
-    exit 0
+    exit $EXIT_OK
   fi
 
 # Fan Status----------------------------------------------------------------------------------------------------------------------------------------
@@ -749,11 +799,11 @@ elif [ "$strPart" == "fans" ]; then
   echo "$ALLOUTPUT|$PERFOUTPUT"
 
   if [ $CRITICAL -eq 1 ]; then
-    exit 2
+    exit $EXIT_CRITICAL
   elif [ $WARNING -eq 1 ]; then
-    exit 1
+    exit $EXIT_WARNING
   else
-    exit 0
+    exit $EXIT_OK
   fi
 
 # System Uptime----------------------------------------------------------------------------------------------------------------------------------------
@@ -764,21 +814,21 @@ elif [ "$strPart" == "systemuptime" ]; then
 
   if [ -z $sysuptime -o -z $netuptime ]; then
     OUTPUT="UNKOWN: Could not get uptime information!"
-    EXIT=3
+    EXIT=$EXIT_UNKOWN
   fi
   if [ "$sysuptime" -le "$strCritical" ]; then
     OUTPUT="CRITICAL: System up since $(date -d @$(( $(date +%s) - $sysuptime )))"
-    EXIT=2
+    EXIT=$EXIT_CRITICAL
   elif [ "$sysuptime" -le "$strWarning" ]; then
     OUTPUT="WARNING: System up since $(date -d @$(( $(date +%s) - $sysuptime )))"
-    EXIT=1
+    EXIT=$EXIT_WARNING
   elif [ "$netuptime" -le "$strCritical" ]; then
     OUTPUT="$OUTPUT CRITICAL: Network up since $(date -d @$(( $(date +%s) - $netuptime )))"
-    EXIT=2
+    EXIT=$EXIT_CRITICAL
   elif [ "$netuptime" -le "$strWarning" ]; then
     OUTPUT="$OUTPUT WARNING: Network up since $(date -d @$(( $(date +%s) - $netuptime )))"
     if [ ! $EXIT -eq 2 ];then
-      EXIT=1
+      EXIT=$EXIT_WARNING
     fi
   else
     OUTPUT="OK: System up since $(date -d @$(( $(date +%s) - $sysuptime ))) - Network up since $(date -d @$(( $(date +%s) - $netuptime )))"
@@ -799,10 +849,10 @@ elif [ "$strPart" == "sysinfo" ]; then
   firmware="$(_snmpgetval .1.3.6.1.2.1.47.1.1.1.1.9.1 | sed 's/^"\(.*\)$/\1/')"
 
   echo "NAS $name, Model $model, Firmware $firmware, Max HD number $hdnum, No. Volume $VOLCOUNT, No. iSCSI LUNs $lunCOUNT"
-  exit 0
+  exit $EXIT_OK
 
 #----------------------------------------------------------------------------------------------------------------------------------------------------
 else
-  echo "Unknown Part!" && exit 3
+  echo "Unknown Part!" && exit $EXIT_UNKNOWN
 fi
-exit 0
+exit $EXIT_OK
